#!/usr/bin/env python3
"""
Convert Wycheproof ECDSA/P-256 P1363 test vector JSON files into a C
header for use by test_wycheproof.c.

Wycheproof supplies the raw message; this script pre-computes the hash
because tv_ecdsa_p256_verify() takes the hash value directly.  The hash
function is read from each test group's 'sha' field (SHA-256, SHA-512,
etc.) so one invocation can merge SHA-256 and SHA-512 vector sets.  The
resulting hash length is encoded in the hex string — the test harness
derives hv_len from that.

All tests are emitted, including those with non-64-byte signatures:
the verifier is expected to reject them on length, and Wycheproof marks
them all "invalid" anyway.

Usage:
  python3 gen_wycheproof.py FILE.json [FILE2.json ...] > wycheproof_vectors.h

Regeneration:
  base=https://raw.githubusercontent.com/C2SP/wycheproof/master/testvectors_v1
  curl -sL $base/ecdsa_secp256r1_sha256_p1363_test.json -o /tmp/wp256.json
  curl -sL $base/ecdsa_secp256r1_sha512_p1363_test.json -o /tmp/wp512.json
  python3 gen_wycheproof.py /tmp/wp256.json /tmp/wp512.json > wycheproof_vectors.h
"""

import sys
import json
import hashlib

HASH_FUNCS = {
    "SHA-256": hashlib.sha256,
    "SHA-384": hashlib.sha384,
    "SHA-512": hashlib.sha512,
    "SHA3-256": hashlib.sha3_256,
    "SHA3-384": hashlib.sha3_384,
    "SHA3-512": hashlib.sha3_512,
}


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def hexwrap(s, width=64, indent='\t  '):
    """Break a long hex string into C-literal fragments."""
    parts = [s[i:i + width] for i in range(0, len(s), width)]
    return ('\n' + indent).join(f'"{p}"' for p in parts)


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    out = sys.stdout
    out.write("/*\n")
    out.write(" * Wycheproof ECDSA/P-256 test vectors (P1363 raw r||s format).\n")
    out.write(" *\n")
    out.write(" * Generated by gen_wycheproof.py from Project Wycheproof.\n")
    out.write(" * Source: https://github.com/C2SP/wycheproof\n")
    out.write(" *\n")
    out.write(" * Input files:\n")
    for fn in sys.argv[1:]:
        out.write(f" *   {fn.split('/')[-1]}\n")
    out.write(" *\n")
    out.write(" * Each vector stores the precomputed message hash (SHA-256 or\n")
    out.write(" * SHA-512 depending on the source group), since the verifier\n")
    out.write(" * under test receives the hash value, not the message.  The\n")
    out.write(" * hash length is implicit in the hex string length.\n")
    out.write(" *\n")
    out.write(" * DO NOT EDIT -- regenerate with gen_wycheproof.py.\n")
    out.write(" */\n\n")

    out.write("struct wp_test {\n")
    out.write("\tint tcId;\n")
    out.write("\tint expect;            /* 1 = valid, 0 = invalid */\n")
    out.write("\tconst char *comment;\n")
    out.write("\tconst char *flags;\n")
    out.write("\tconst char *pub;       /* hex, 65-byte uncompressed point */\n")
    out.write("\tconst char *hash;      /* hex, 32 or 64 bytes depending on sha */\n")
    out.write("\tconst char *sig;       /* hex, variable length (usually 64 bytes) */\n")
    out.write("};\n\n")

    out.write("static const struct wp_test WP_TESTS[] = {\n")

    n_tests = 0
    for fn in sys.argv[1:]:
        with open(fn) as f:
            data = json.load(f)

        assert data["algorithm"] == "ECDSA"
        assert data["schema"] == "ecdsa_p1363_verify_schema_v1.json"

        short_fn = fn.split("/")[-1]
        out.write(f"\n/* ---- {short_fn} "
                  f"({data.get('numberOfTests', '?')} tests) ---- */\n\n")

        for group in data["testGroups"]:
            pk = group["publicKey"]["uncompressed"]
            assert len(pk) == 130  # 65 bytes hex

            sha_name = group["sha"]
            hash_func = HASH_FUNCS[sha_name]

            for t in group["tests"]:
                tcId = t["tcId"]
                msg = bytes.fromhex(t["msg"])
                h = hash_func(msg).hexdigest()
                sig = t["sig"]
                result = t["result"]
                comment = t.get("comment", "")
                flags = ",".join(t.get("flags", []))

                # "acceptable" does not appear in these files, but be
                # defensive: for ECDSA-verify it means valid-per-spec
                # with some unusual property.
                if result == "valid":
                    expect = 1
                elif result == "invalid":
                    expect = 0
                elif result == "acceptable":
                    expect = 1
                else:
                    raise ValueError(f"unknown result: {result!r}")

                out.write("{\n")
                out.write(f"\t{tcId}, {expect},\n")
                out.write(f'\t"{cesc(comment)}",\n')
                out.write(f'\t"{cesc(flags)}",\n')
                out.write(f'\t{hexwrap(pk)},\n')
                out.write(f'\t{hexwrap(h)},\n')
                out.write(f'\t{hexwrap(sig)}\n')
                out.write("},\n")
                n_tests += 1

    out.write("};\n\n")
    out.write(f"#define WP_NUM_TESTS {n_tests}\n")


if __name__ == "__main__":
    main()
