#!/usr/bin/env python3
"""
Generate test vectors for the all-ZMM signer, at every layer.

Each layer gets its own vector file so regressions are caught as
close to the bug as possible — if fe_mul breaks, you see it in
fe_mul's vectors, not as a mysterious sign-vs-verify mismatch.

Output: sign_vectors.h (C header, #include-able by the test harness).
"""
import os, hashlib, sys
sys.path.insert(0, os.path.dirname(__file__))
from sign_zmm_model import (
    p, n, b_curve, Gx, Gy,
    to_limbs, from_limbs, ifma_mul_5x5, propagate,
    fe_mul, fe_add, fe_sub, fe_inv,
    pt_add, ladder, cswap, sign,
)

RNG = os.urandom

def rand256(mod=None):
    v = int.from_bytes(RNG(32), 'big')
    return v % mod if mod else v

def emit_limbs(name, x, f):
    """Emit a 5×52 limb array, padded to 8 for ZMM alignment."""
    L = to_limbs(x) + [0, 0, 0]
    print(f"  {{{', '.join(f'0x{l:013x}ULL' for l in L)}}}; /* {name} */", file=f)

# ======================================================================
with open('sign_vectors.h', 'w') as f:
    print("/* AUTO-GENERATED by gen_sign_vectors.py.  DO NOT EDIT. */", file=f)
    print("#include <stdint.h>", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 0: constants.  Never change, but having them here catches
    # endianness/limb-order mistakes in the C loader.
    # ------------------------------------------------------------------
    print("/* === CONSTANTS (5×52 limbs, lane 0 = least significant) === */", file=f)
    print("static const uint64_t C_P[8]    =", file=f); emit_limbs("p", p, f)
    print("static const uint64_t C_N[8]    =", file=f); emit_limbs("n", n, f)
    print("static const uint64_t C_B[8]    =", file=f); emit_limbs("b", b_curve, f)
    print("static const uint64_t C_GX[8]   =", file=f); emit_limbs("Gx", Gx, f)
    print("static const uint64_t C_GY[8]   =", file=f); emit_limbs("Gy", Gy, f)
    print("static const uint64_t C_F260P[8]=", file=f); emit_limbs("2^260 mod p", pow(2,260,p), f)
    print("static const uint64_t C_F260N[8]=", file=f); emit_limbs("2^260 mod n", pow(2,260,n), f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 1: IFMA schoolbook (unreduced 10-limb product).  This is
    # the ONE place where the AVX-512 lane-shift logic can go wrong
    # in ways that are hard to see — the products are right, but they
    # land in the wrong limbs.  1000 random + edge cases.
    # ------------------------------------------------------------------
    print("/* === LAYER 1: IFMA SCHOOLBOOK (unreduced 10-limb) === */", file=f)
    print("/* Each: a[5], b[5], t[10].  t is the raw accumulated product", file=f)
    print(" * BEFORE any propagation — tests vpmadd52 + valignq alignment. */", file=f)
    edges = [
        (0, 0), (1, 1), (p-1, p-1), (1, p-1),
        ((1<<52)-1, (1<<52)-1),     # max single limb × itself
        (Gx, Gy),
        ((1<<260)-1 % p, 2),        # max reduced × small
    ]
    N_SCHOOL = 200
    vectors = list(edges) + [(rand256(p), rand256(p)) for _ in range(N_SCHOOL-len(edges))]
    print(f"#define N_SCHOOLBOOK {len(vectors)}", file=f)
    print("static const struct { uint64_t a[5], b[5], t[10]; } V_SCHOOL[] = {", file=f)
    for a, b in vectors:
        aL, bL = to_limbs(a), to_limbs(b)
        tL = ifma_mul_5x5(aL, bL)
        a_s = ','.join(f'0x{x:x}' for x in aL)
        b_s = ','.join(f'0x{x:x}' for x in bL)
        t_s = ','.join(f'0x{x:x}' for x in tL)
        print(f"  {{{{{a_s}}}, {{{b_s}}}, {{{t_s}}}}},", file=f)
    print("};", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 2: fe_mul mod p (full reduce).  Tests the fold + propagate
    # + conditional-subtract chain.  Output is CANONICAL (< p).
    # ------------------------------------------------------------------
    print("/* === LAYER 2: fe_mul mod p (canonical output) === */", file=f)
    N_MUL = 500
    vectors = list(edges) + [(rand256(p), rand256(p)) for _ in range(N_MUL-len(edges))]
    print(f"#define N_FEMUL {len(vectors)}", file=f)
    print("static const struct { uint64_t a[5], b[5], c[5]; } V_FEMUL[] = {", file=f)
    for a, b in vectors:
        c = a * b % p
        a_s = ','.join(f'0x{x:x}' for x in to_limbs(a))
        b_s = ','.join(f'0x{x:x}' for x in to_limbs(b))
        c_s = ','.join(f'0x{x:x}' for x in to_limbs(c))
        print(f"  {{{{{a_s}}}, {{{b_s}}}, {{{c_s}}}}},", file=f)
    print("};", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 3: cswap.  Trivial, but the bit-extraction from the ZMM
    # holding k can go wrong (which lane? which bit?).
    # ------------------------------------------------------------------
    print("/* === LAYER 3: cswap === */", file=f)
    print("/* Each: bit, a[5], b[5], a_out[5], b_out[5]. */", file=f)
    cs = [(0, Gx, Gy), (1, Gx, Gy), (0, 0, p-1), (1, p-1, 0)]
    print(f"#define N_CSWAP {len(cs)}", file=f)
    print("static const struct { int bit; uint64_t a[5],b[5],ao[5],bo[5]; } V_CSWAP[] = {", file=f)
    for bit, a, b in cs:
        ao, bo = cswap(bit, to_limbs(a), to_limbs(b))
        def L(x): return ','.join(f'0x{v:x}' for v in x[:5])
        print(f"  {{{bit}, {{{L(to_limbs(a))}}}, {{{L(to_limbs(b))}}}, {{{L(ao)}}}, {{{L(bo)}}}}},", file=f)
    print("};", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 4: pt_add (RCB).  Input/output as (X,Y,Z) projective.
    # Includes the edge cases that completeness is supposed to handle.
    # ------------------------------------------------------------------
    print("/* === LAYER 4: pt_add (RCB complete) === */", file=f)
    G = (to_limbs(Gx), to_limbs(Gy), to_limbs(1))
    INF = (to_limbs(0), to_limbs(1), to_limbs(0))
    G2 = pt_add(G, G)
    G3 = pt_add(G2, G)
    negG = (to_limbs(Gx), to_limbs(p-Gy), to_limbs(1))
    pt_cases = [
        ("G+G", G, G),
        ("G+2G", G, G2),
        ("inf+G", INF, G),
        ("G+inf", G, INF),
        ("G+(-G)", G, negG),
        ("inf+inf", INF, INF),
        ("2G+3G", G2, G3),
    ]
    # + random pairs (both components reduced projective points)
    for i in range(20):
        k1, k2 = rand256(n) or 1, rand256(n) or 1
        P = ladder(k1, (Gx,Gy)); Q = ladder(k2, (Gx,Gy))
        pt_cases.append((f"rand{i}", P, Q))
    print(f"#define N_PTADD {len(pt_cases)}", file=f)
    print("static const struct { uint64_t px[5],py[5],pz[5],qx[5],qy[5],qz[5],rx[5],ry[5],rz[5]; } V_PTADD[] = {", file=f)
    for name, P, Q in pt_cases:
        R = pt_add(P, Q)
        def L(x): return ','.join(f'0x{v:x}' for v in x[:5])
        print(f"  /* {name} */", file=f)
        print(f"  {{{{{L(P[0])}}}, {{{L(P[1])}}}, {{{L(P[2])}}}, {{{L(Q[0])}}}, {{{L(Q[1])}}}, {{{L(Q[2])}}}, {{{L(R[0])}}}, {{{L(R[1])}}}, {{{L(R[2])}}}}},", file=f)
    print("};", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 5: ladder (k·G).  Output in projective; test converts to
    # affine to compare (or compares projectively via cross-mult).
    # ------------------------------------------------------------------
    print("/* === LAYER 5: Montgomery ladder (k·G, projective out) === */", file=f)
    ladder_ks = [1, 2, 3, 7, n-1, n//2,
                 0xdeadbeef,
                 0xC9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721]  # RFC 6979 d
    ladder_ks += [rand256(n) or 1 for _ in range(12)]
    print(f"#define N_LADDER {len(ladder_ks)}", file=f)
    print("static const struct { uint64_t k[5], rx[5], ry[5], rz[5]; } V_LADDER[] = {", file=f)
    for k in ladder_ks:
        R = ladder(k, (Gx, Gy))
        def L(x): return ','.join(f'0x{v:x}' for v in x[:5])
        print(f"  {{{{{L(to_limbs(k))}}}, {{{L(R[0])}}}, {{{L(R[1])}}}, {{{L(R[2])}}}}},", file=f)
    print("};", file=f)
    print(file=f)

    # ------------------------------------------------------------------
    # Layer 6: full sign.  RFC 6979 + random (d,k,e).  Output is
    # (r,s) as integers — the final public values.
    # ------------------------------------------------------------------
    print("/* === LAYER 6: full ECDSA sign (d,k,e → r,s) === */", file=f)
    d_rfc = 0xC9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721
    sign_cases = [
        # (name, d, k, e, r, s) — r,s None = compute from model
        ("RFC6979-sample", d_rfc,
         0xA6E3C57DD01ABE90086538398355DD4C3B17AA873382B0F24D6129493D8AAD60,
         int.from_bytes(hashlib.sha256(b'sample').digest(),'big'),
         0xEFD48B2AACB6A8FD1140DD9CD45E81D69D2C877B56AAF991C34D0EA84EAF3716,
         0xF7CB1C942D657C41D436C7A1B6E29F65F3E900DBB9AFF4064DC4AB2F843ACDA8),
        ("RFC6979-test", d_rfc,
         0xD16B6AE827F17175E040871A1C7EC3500192C4C92677336EC2537ACAEE0008E0,
         int.from_bytes(hashlib.sha256(b'test').digest(),'big'),
         0xF1ABB023518351CD71D881567B1EA663ED3EFCF6C5132B354F28D3B0B7D38367,
         0x019F4113742A2B14BD25926B49C649155F267E60D3814B4C0CC84250E46F0083),
    ]
    for i in range(30):
        d = rand256(n) or 1
        k = rand256(n) or 1
        e = rand256(n)
        r, s = sign(d, k, e)
        sign_cases.append((f"rand{i}", d, k, e, r, s))
    print(f"#define N_SIGN {len(sign_cases)}", file=f)
    print("static const struct { uint64_t d[5],k[5],e[5],r[5],s[5]; } V_SIGN[] = {", file=f)
    for name, d, k, e, r, s in sign_cases:
        # Verify each (catches model-vs-model regressions if sign_zmm_model changes)
        got = sign(d, k, e)
        assert got == (r, s), f"{name}: model regression"
        def L(x): return ','.join(f'0x{v:x}' for v in to_limbs(x))
        print(f"  /* {name} */", file=f)
        print(f"  {{{{{L(d)}}}, {{{L(k)}}}, {{{L(e)}}}, {{{L(r)}}}, {{{L(s)}}}}},", file=f)
    print("};", file=f)

print(f"wrote sign_vectors.h")
print(f"  schoolbook: {N_SCHOOL} vectors")
print(f"  fe_mul:     {N_MUL} vectors")
print(f"  cswap:      {len(cs)} vectors")
print(f"  pt_add:     {len(pt_cases)} vectors (including completeness edge cases)")
print(f"  ladder:     {len(ladder_ks)} vectors")
print(f"  sign:       {len(sign_cases)} vectors (2 RFC 6979 + {len(sign_cases)-2} random)")
