/* Correctness harness for limb11_mul.S.
 * Checks fe_mul11 against Python-generated reference vectors.
 * Vectors: MontMul(a, b) = a*b / R mod p, with R = 2^264, p = P-256. */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

extern void fe_mul11(int64_t *dst, const int64_t *a, const int64_t *b,
                     const int64_t *m);

/* v5+ is self-contained re: rcx (uses lea, not mov cl). */

#define K 11
#define W 24

/* P-256 p in 11×24-bit limbs, little-endian. */
static const int64_t P_LIMBS[K] = {
    0xffffff, 0xffffff, 0xffffff, 0xffffff, 0, 0, 0, 0, 1, 0xffff00, 0xffff
};

/* Vectors generated by range_limbs.py — (a, b, a*b/R mod p) as limbs.
 * Each vector is 3*K int64s. */
#include "limb11_vectors.h"

static int limbs_eq_mod_p(const int64_t *a, const int64_t *b) {
    /* Reconstruct both as 320-bit integers (conservative), reduce mod p,
     * compare. Simple schoolboy approach — correctness, not speed. */
    /* Actually: convert both to a canonical integer by carry-propagating,
     * then compare. The test vectors give CANONICAL expected output
     * (limbs in [0, 2^24), value in [0, p)). fe_mul11 output has limbs
     * 0..9 in [0, 2^24) and limb 10 signed, value in some [-Cp, Cp]
     * range. To compare: fully reduce a to [0, p) and compare to b. */
    int64_t t[K];
    memcpy(t, a, sizeof t);
    /* Carry-propagate t. */
    int64_t carry = 0;
    for (int k = 0; k < K; k++) {
        int64_t v = t[k] + carry;
        t[k] = v & ((1L << W) - 1);
        carry = v >> W;
    }
    t[K-1] += carry << W;
    /* Now t is semi-canonical. t[K-1] may be out of [0, 2^24). The
     * represented value is in some range; bring to [0, p). */
    /* While negative (top limb < 0): add p. While ≥ p: subtract p.
     * "≥ p" check: lexicographic from top. */
    for (int iter = 0; iter < 20; iter++) {
        /* Re-carry after each add/sub. */
        carry = 0;
        for (int k = 0; k < K; k++) {
            int64_t v = t[k] + carry;
            t[k] = v & ((1L << W) - 1);
            carry = v >> W;
        }
        t[K-1] += carry << W;
        if (t[K-1] < 0) {
            for (int k = 0; k < K; k++) t[k] += P_LIMBS[k];
            continue;
        }
        /* Compare to p from top. */
        int ge = 0;
        for (int k = K-1; k >= 0; k--) {
            if (t[k] > P_LIMBS[k]) { ge = 1; break; }
            if (t[k] < P_LIMBS[k]) { ge = 0; break; }
            /* equal: continue */
            if (k == 0) ge = 1;  /* exactly equal to p */
        }
        if (ge) {
            for (int k = 0; k < K; k++) t[k] -= P_LIMBS[k];
            continue;
        }
        break;
    }
    /* Now t should be canonical [0, p). Compare to b. */
    for (int k = 0; k < K; k++)
        if (t[k] != b[k]) return 0;
    return 1;
}

int main(void) {
    int pass = 0, fail = 0;
    for (int i = 0; i < NUM_VECTORS; i++) {
        const int64_t *a = VECTORS[i];
        const int64_t *b = VECTORS[i] + K;
        const int64_t *exp = VECTORS[i] + 2*K;
        int64_t got[K];
        fe_mul11(got, a, b, P_LIMBS);
        if (limbs_eq_mod_p(got, exp)) {
            pass++;
        } else {
            fail++;
            if (fail <= 3) {
                printf("FAIL vector %d:\n", i);
                printf("  a   = {");
                for (int k=0;k<K;k++) printf("0x%lx%s", a[k], k<K-1?",":"");
                printf("}\n  b   = {");
                for (int k=0;k<K;k++) printf("0x%lx%s", b[k], k<K-1?",":"");
                printf("}\n  exp = {");
                for (int k=0;k<K;k++) printf("0x%lx%s", exp[k], k<K-1?",":"");
                printf("}\n  got = {");
                for (int k=0;k<K;k++) printf("0x%lx%s", got[k], k<K-1?",":"");
                printf("}\n");
            }
        }
    }
    printf("%d/%d passed\n", pass, pass+fail);
    return fail != 0;
}
