/*
 * Wycheproof test driver for tv_ecdsa_p256_verify().
 *
 * Runs all vectors from the P1363 (raw r||s) test files for P-256
 * with SHA-256 and SHA-512.  Vectors are embedded in
 * wycheproof_vectors.h (generated by gen_wycheproof.py) with
 * Hash(msg) pre-computed, since the function under test takes a
 * hash value rather than a message.  The SHA-512 vectors exercise
 * the 64-byte hash truncation path.
 *
 * These tests target specific bug classes that have historically
 * broken ECDSA verifiers:
 *
 *   PointDuplication
 *       Point addition hits the P + P or P + (-P) degenerate case
 *       during the final u1*G + u2*Q combination. Naive addition
 *       formulas produce wrong results here (usually 0/0). Includes
 *       the case where Q shares its x-coordinate with G.
 *
 *   EdgeCaseShamirMultiplication
 *       Exercises corner cases in Shamir's trick / Straus
 *       double-scalar multiplication that are easy to get wrong.
 *
 *   ModularInverse
 *       s^-1 mod n lands on values that stress extended-GCD or
 *       Fermat-based inversion.
 *
 *   SmallRandS
 *       VALID signatures with r=1, s=1, r=2 etc. A verifier that
 *       silently truncates or has off-by-one handling of tiny
 *       inputs will reject these wrongly.
 *
 *   SpecialCaseHash
 *       Messages whose SHA-256 digest has unusual structure: many
 *       leading zeros, value near n, bit patterns that trigger
 *       carry propagation bugs in the e*s^-1 mod n reduction.
 *
 *   EdgeCasePublicKey
 *       Public key x or y very small / very large / many trailing
 *       zero bits. Stresses field arithmetic near the ends of [0,p).
 *
 *   RangeCheck / IntegerOverflow
 *       r or s replaced by r+n, r+2^256, r+2^320. These arrive with
 *       sig_len != 64 so they're rejected by length check alone, but
 *       they stay in to confirm that path works.
 *
 *   SignatureSize
 *       Truncated r||s (2, 16, 26, 32, 40 bytes). Same: length
 *       check rejects, but belt-and-suspenders.
 *
 *   ArithmeticError
 *       Broad catch-all for vectors crafted to trigger carry-
 *       propagation and reduction bugs in field/scalar arithmetic.
 *
 * Any vector that fails is printed with its tcId, comment, and flags
 * so the bug class is immediately visible.
 */

#include <stdio.h>
#include <string.h>

#ifndef tv_ecdsa_p256_verify
#include "tv_ecdsa.h"
#endif

#include "wycheproof_vectors.h"

static int hexval(int c)
{
	if (c >= '0' && c <= '9') return c - '0';
	if (c >= 'a' && c <= 'f') return c - 'a' + 10;
	if (c >= 'A' && c <= 'F') return c - 'A' + 10;
	return -1;
}

static size_t hex2bin(unsigned char *dst, const char *src)
{
	size_t n = 0;
	while (src[0] && src[1]) {
		int hi = hexval(src[0]);
		int lo = hexval(src[1]);
		if (hi < 0 || lo < 0) break;
		dst[n++] = (unsigned char)((hi << 4) | lo);
		src += 2;
	}
	return n;
}

int main(void)
{
	int fails = 0;
	int pass_valid = 0, pass_invalid = 0;

	printf("== Wycheproof ECDSA P-256 (P1363, SHA-256 + SHA-512) ==\n");
	printf("   %d test vectors\n\n", WP_NUM_TESTS);

	for (int i = 0; i < WP_NUM_TESTS; i++) {
		const struct wp_test *t = &WP_TESTS[i];

		/*
		 * Wycheproof sigs go up to 82 bytes (r+2^320).
		 * Hash is 32 bytes for SHA-256 vectors, 64 for SHA-512.
		 */
		unsigned char pub[65], hash[64], sig[128];
		size_t publen, hashlen, siglen;
		int got;

		publen  = hex2bin(pub,  t->pub);
		hashlen = hex2bin(hash, t->hash);
		siglen  = hex2bin(sig,  t->sig);

		got = tv_ecdsa_p256_verify(sig, siglen, pub, publen,
			hash, hashlen);

		if (got == t->expect) {
			if (t->expect) pass_valid++; else pass_invalid++;
		} else {
			printf("  FAIL  tcId=%d  got=%d expect=%d\n",
				t->tcId, got, t->expect);
			printf("        %s\n", t->comment);
			printf("        flags: %s\n", t->flags);
			printf("        pub:  %s\n", t->pub);
			printf("        hash: %s\n", t->hash);
			printf("        sig:  %s (len=%zu)\n", t->sig, siglen);
			fails++;
		}
	}

	printf("\n%s: %d tests, %d failures (%d valid + %d invalid pass)\n",
		fails ? "FAILED" : "OK",
		WP_NUM_TESTS, fails, pass_valid, pass_invalid);

	return fails ? 1 : 0;
}
