[package]
name = "p256_verify"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3

[profile.bench]
lto = "fat"
codegen-units = 1


[[bench]]
name = "fe_mul"
harness = false

[[bench]]
name = "verify"
harness = false

[dev-dependencies]
regex = "1"

[[bench]]
name = "wycheproof"
harness = false
