#!/usr/bin/env python3
"""Generate fe_mul5 test vectors. Triples of (a, b, MontMul(a,b) mod p).
Includes both canonical and lazy-carry (signed, grown) inputs to cover
the full input range the RCB formula produces."""

import random

P = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
N = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551
W, K = 56, 5
MASK = (1 << W) - 1
R = 1 << (K * W)
Rinv = pow(R, -1, P)

def split(x):
    return [(x >> (W*i)) & MASK for i in range(K)]

def join(limbs):
    return sum(v << (W*i) for i, v in enumerate(limbs))

def mont_mul(a_limbs, b_limbs):
    """Reference MontMul: join, multiply, reduce, split."""
    a = join(a_limbs) % P
    b = join(b_limbs) % P
    return split((a * b * Rinv) % P)

random.seed(42)
vecs = []

# Canonical random inputs.
for _ in range(50):
    a = random.randrange(P)
    b = random.randrange(P)
    al, bl = split(a), split(b)
    vecs.append((al, bl, mont_mul(al, bl)))

# Lazy-carry inputs: limbs grown beyond 56 bits via carry-borrow perturbation.
# l[i] += k*2^W, l[i+1] -= k preserves value exactly. With W=56 and
# |k| ≤ 31, |perturbation| ≤ 2^61 (matches range_proof bound) and
# the sum still fits signed-int64.
for _ in range(40):
    a = random.randrange(P)
    b = random.randrange(P)
    al, bl = split(a), split(b)
    def perturb(l):
        l = list(l)
        for _ in range(3):
            i = random.randrange(K-1)
            k = random.randrange(-31, 32)
            l[i]   += k << W
            l[i+1] -= k
        # Fits int64 check (avoid silent overflow in C).
        for v in l: assert -(1<<62) < v < (1<<62), v
        return l
    alp, blp = perturb(al), perturb(bl)
    assert join(alp) == join(al) and join(blp) == join(bl), "perturb broke value"
    vecs.append((alp, blp, mont_mul(alp, blp)))

# Values beyond p (≤ 4p — RCB feeds these back in).
for _ in range(10):
    a = random.randrange(P) + random.randrange(4) * P
    b = random.randrange(P) + random.randrange(4) * P
    al, bl = split(a), split(b)
    vecs.append((al, bl, mont_mul(al, bl)))

# Edge cases.
zero = split(0)
one  = split(1)
pm1  = split(P-1)
r_mod_p = split(R % P)
vecs += [
    (zero, zero, mont_mul(zero, zero)),
    (one,  one,  mont_mul(one,  one)),
    (one,  r_mod_p, mont_mul(one, r_mod_p)),   # = 1
    (pm1,  pm1,  mont_mul(pm1,  pm1)),
    (split(2), split(R % P), mont_mul(split(2), split(R % P))),  # = 2
]

# Mod-n vectors too (separate section).
Rinv_n = pow(R, -1, N)
def mont_mul_n(a_limbs, b_limbs):
    a = join(a_limbs) % N
    b = join(b_limbs) % N
    return split((a * b * Rinv_n) % N)

nvecs = []
for _ in range(20):
    a = random.randrange(N)
    b = random.randrange(N)
    al, bl = split(a), split(b)
    nvecs.append((al, bl, mont_mul_n(al, bl)))

# Emit
print("/* Generated by gen_vectors.py. fe_mul5 test vectors, 5×56. */")
print(f"#define NUM_VECTORS {len(vecs)}")
print(f"static const int64_t VECTORS[NUM_VECTORS][3*{K}] = {{")
for a, b, e in vecs:
    row = list(a) + list(b) + list(e)
    print("  {" + ", ".join(f"{v}L" for v in row) + "},")
print("};")
print()
print(f"#define NUM_NVECTORS {len(nvecs)}")
print(f"static const int64_t NVECTORS[NUM_NVECTORS][3*{K}] = {{")
for a, b, e in nvecs:
    row = list(a) + list(b) + list(e)
    print("  {" + ", ".join(f"{v}L" for v in row) + "},")
print("};")
