#!/usr/bin/env python3
"""Generate fe_mul5 test vectors. Triples of (a, b, MontMul(a,b) mod p).
Includes both canonical and lazy-carry (signed, grown) inputs to cover
the full input range the RCB formula produces."""

import random

P = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
N = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551
W, K = 54, 5
MASK = (1 << W) - 1
R = 1 << (K * W)
Rinv = pow(R, -1, P)

def split(x):
    return [(x >> (W*i)) & MASK for i in range(K)]

def join(limbs):
    return sum(v << (W*i) for i, v in enumerate(limbs))

def mont_mul(a_limbs, b_limbs):
    """Reference MontMul: join, multiply, reduce, split."""
    a = join(a_limbs) % P
    b = join(b_limbs) % P
    return split((a * b * Rinv) % P)

random.seed(42)
vecs = []

# Canonical random inputs.
for _ in range(50):
    a = random.randrange(P)
    b = random.randrange(P)
    al, bl = split(a), split(b)
    vecs.append((al, bl, mont_mul(al, bl)))

# Lazy-carry inputs: limbs grown to ±2^59 (RCB worst case per range_proof).
# Value stays in a ~4p range.
for _ in range(40):
    a = random.randrange(P)
    b = random.randrange(P)
    al, bl = split(a), split(b)
    # Perturb: add noise to one limb, subtract equivalent from next.
    # Keeps value congruent mod P but limbs go signed/large.
    def perturb(l):
        l = list(l)
        for _ in range(3):
            i = random.randrange(K-1)
            d = random.randrange(-(1<<57), 1<<57)
            l[i] += d << W
            l[i+1] -= d
        return l
    alp, blp = perturb(al), perturb(bl)
    # Verify perturbation preserved value
    assert join(alp) % P == a, "perturb broke a"
    assert join(blp) % P == b, "perturb broke b"
    vecs.append((alp, blp, mont_mul(alp, blp)))

# Edge cases.
zero = split(0)
one  = split(1)
pm1  = split(P-1)
r_mod_p = split(R % P)
vecs += [
    (zero, zero, mont_mul(zero, zero)),
    (one,  one,  mont_mul(one,  one)),
    (one,  r_mod_p, mont_mul(one, r_mod_p)),   # = 1
    (pm1,  pm1,  mont_mul(pm1,  pm1)),
    (split(2), split(R % P), mont_mul(split(2), split(R % P))),  # = 2
]

# Mod-n vectors too (separate section).
Rinv_n = pow(R, -1, N)
def mont_mul_n(a_limbs, b_limbs):
    a = join(a_limbs) % N
    b = join(b_limbs) % N
    return split((a * b * Rinv_n) % N)

nvecs = []
for _ in range(20):
    a = random.randrange(N)
    b = random.randrange(N)
    al, bl = split(a), split(b)
    nvecs.append((al, bl, mont_mul_n(al, bl)))

# Emit
print("/* Generated by gen_vectors.py. fe_mul5 test vectors, 5×54. */")
print(f"#define NUM_VECTORS {len(vecs)}")
print(f"static const int64_t VECTORS[NUM_VECTORS][3*{K}] = {{")
for a, b, e in vecs:
    row = list(a) + list(b) + list(e)
    print("  {" + ", ".join(f"{v}L" for v in row) + "},")
print("};")
print()
print(f"#define NUM_NVECTORS {len(nvecs)}")
print(f"static const int64_t NVECTORS[NUM_NVECTORS][3*{K}] = {{")
for a, b, e in nvecs:
    row = list(a) + list(b) + list(e)
    print("  {" + ", ".join(f"{v}L" for v in row) + "},")
print("};")
